default_column = "backlog"
id = "2RWmsIPz"
kan_schema = "board/8"
name = "main"

[card_display]
  type_indicator = "type"

[[columns]]
  card_ids = ["2RcNmu4Y", "2RcOMyCT", "2Rpd00De"]
  color = "#a855f7"
  name = "undecided"

[[columns]]
  color = "#6b7280"
  name = "backlog"

[[columns]]
  color = "#3b82f6"
  name = "next"

[[columns]]
  color = "#f59e0b"
  name = "in-progress"

[[columns]]
  color = "#10b981"
  name = "done"

[custom_fields]
  [custom_fields.type]
    type = "enum"

    [[custom_fields.type.options]]
      color = "#ef4444"
      value = "bug"

    [[custom_fields.type.options]]
      color = "#3b82f6"
      value = "enhancement"

    [[custom_fields.type.options]]
      color = "#22c55e"
      value = "feature"

    [[custom_fields.type.options]]
      color = "#6b7280"
      value = "chore"
