kan_schema = "board/2"
id = "2RWmsIPz"
name = "main"
default_column = "backlog"

[[columns]]
  name = "undecided"
  color = "#a855f7"
  card_ids = ["2RcNmu4Y", "2RcOMyCT", "2Rpd00De"]

[[columns]]
  name = "backlog"
  color = "#6b7280"

[[columns]]
  name = "next"
  color = "#3b82f6"

[[columns]]
  name = "in-progress"
  color = "#f59e0b"

[[columns]]
  name = "done"
  color = "#10b981"

[custom_fields]
  [custom_fields.type]
    type = "enum"

    [[custom_fields.type.options]]
      value = "bug"
      color = "#ef4444"

    [[custom_fields.type.options]]
      value = "enhancement"
      color = "#3b82f6"

    [[custom_fields.type.options]]
      value = "feature"
      color = "#22c55e"

    [[custom_fields.type.options]]
      value = "chore"
      color = "#6b7280"

[card_display]
  type_indicator = "type"
